version: '3.8'

x-default-app:
  &default-app
    build:
      dockerfile: ./Dockerfile
      # If you want to try the prod build, you need to set the user to root,
      # because docker-compose volume will override the permissions of the app folder
      target: dev
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/code
    stdin_open: true
    tty: true

services:
  server:
    <<: *default-app
    ports:
      - 8000:8000

  postgres:
    image: "postgres:16-alpine"
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=waltz
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
