name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:


jobs:
  ci:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: waltz
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Load pip cache
        id: pip-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: pip-${{ hashFiles('./requirements/*.txt') }}

      - name: Install Dependencies
        run: pip install -r ./requirements/dev.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'

      - name: Load pre-commit cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit hooks
        run: make lint
